### ISSUE TITLE
不知道为何使用了proxychains4 vapor build, 依然无法build 成功?

### ISSUE THREAD

**Issue by flyweights** [isaced/NSPress#1]
我proxychains4 brew 之类操作就是杠杠的...难道只能使用VPN? 大大是如何操作的呢?

**Comment by isaced** [comment]
之前我也卡在安装很久，甚至给 vapor/toolbox 提了个 [issue](https://github.com/vapor/toolbox/issues/111)，后来不知为啥又可以了，感觉还是网络问题，使用全局 VPN 试试呢?

**Comment by flyweights** [comment]
你说的没错,因为手上没有vpn,于是我换了广东电信,苦等了一个小时,终于下完了,Demo中.build文件大概250兆左右,但是全部都是从github慢慢的拉下来.........................中途如果出来点问题,又要重新再来,看来还是需要VPN

**Comment by isaced** [comment]
设上 Terminal 的 HTTP 代理会好很多

```
export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;
```
